#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import unittest

import os
import tempfile

import model_compiler_for_papyrusrt.generator.top_cmakelists_generator as top_cmakelists_generator


class TestTopCMakeListsGenerator(unittest.TestCase):

    def test_typical_1(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            obj = top_cmakelists_generator.TopCMakeListsGenerator(tmpdir, ['PingPongNode', 'SampleNode'])
            expected_str = '''
# @brief Build script for Papyrus-RT project
#
# Do NOT edit!!!
# Generated by the Model Compiler for Papyrus-RT

add_subdirectory(PingPongNode)
add_subdirectory(SampleNode)

'''[1:]

            self.assertEqual(expected_str, obj._get_str())

            obj.generate()
            self.assertEqual(True, os.path.isfile(tmpdir + os.sep + 'CMakeLists.txt'))


    def test_typical_2(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            obj = top_cmakelists_generator.TopCMakeListsGenerator(tmpdir, [])
            expected_str = '''
# @brief Build script for Papyrus-RT project
#
# Do NOT edit!!!
# Generated by the Model Compiler for Papyrus-RT


'''[1:]

            self.assertEqual(expected_str, obj._get_str())

            obj.generate()
            self.assertEqual(True, os.path.isfile(tmpdir + os.sep + 'CMakeLists.txt'))


if __name__ == '__main__':
    # executed
    unittest.main()
